require_relative '../config/environment.rb'

def reload
  load 'config/environment.rb'
end

#Airbnb

# nyc1=Listing.new("New York")
# nyc2=Listing.new("New York")
# cali=Listing.new("San Diego")
# james=Guest.new("James")
# jeanne=Guest.new("Jeanne")
# ada=Guest.new("Ada")
# soren=Guest.new("Soren")
# james2=Guest.new("James")
# trip1=Trip.new(james, nyc1)
# trip2=Trip.new(james, cali)
# trip3=Trip.new(jeanne, nyc2)
# trip4=Trip.new(jeanne, nyc2)
# trip5=Trip.new(ada, cali)
# trip6=Trip.new(soren, nyc2)

# bakery

# bakery1=Bakery.new("Sunshine")
# bakery2=Bakery.new("By the Way")
# bakery3=Bakery.new("Cakes and More")
# cake1=Dessert.new("Chocolate Cake", bakery1)
# cake2=Dessert.new("Lemon Cake", bakery1)
# cake3=Dessert.new("Coconut Cake", bakery2)
# cake4=Dessert.new("Banana Cake", bakery3)
# flour1=Ingredient.new("Flour", 150, cake1)
# flour2=Ingredient.new("Flour", 150, cake2)
# flour3=Ingredient.new("Flour", 150, cake3)
# flour4=Ingredient.new("Flour", 150, cake4)
# oil1=Ingredient.new("Coconut Oil", 300, cake3)
# oil2=Ingredient.new("Olive Oil", 250, cake2)
# egg=Ingredient.new("Eggs", 310, cake3)
# sugar=Ingredient.new("Sugar", 100, cake4)

# lyft
# pass1=Passenger.new("James")
# pass2=Passenger.new("Jeanne")
# pass3=Passenger.new("Ada")
# pass4=Passenger.new("Soren")
# driv1=Driver.new("Aleks")
# driv2=Driver.new("Teddy")
# driv3=Driver.new("Ginny")
# driv4=Driver.new("David")
# trip1=Ride.new(pass1, driv2, 14.3)
# trip2=Ride.new(pass2, driv2, 117.3)
# trip3=Ride.new(pass3, driv1, 35.8)
# trip4=Ride.new(pass4, driv3, 44.4)
# trip5=Ride.new(pass4, driv3, 450.1)
# trip6=Ride.new(pass4, driv4, 3.8)

# imdb
# actor1=Actor.new("Claire Foy")
# actor2=Actor.new("Jude Law")
# actor3=Actor.new("Anthony Hopkins")
# actor4=Actor.new("Mel Brooks")
# actor5=Actor.new("Henry Winkler")
# actor6=Actor.new("Alyson Hannigan")
# actor7=Actor.new("Michael Clark Duncan")
# movie1=Movie.new("Avengers")
# movie2=Movie.new("Rom Com")
# show1=Show.new("Avengers")
# show2=Show.new("Game of Thrones")
# show3=Show.new("The Good Place")
# char1=Character.new("Iron Man", actor2)
# char2=Character.new("The Thing", actor3)
# char3=Character.new("Thanos", actor4)
# char4=Character.new("Captain America", actor5)
# char5=Character.new("Black Widow", actor1)
# char6=Character.new("Pepper Pots", actor6)
# char7=Character.new("Roger", actor7)
# char8=Character.new("Dean", actor2)
# char9=Character.new("Tyrian", actor2)
# char10=Character.new("Jon Snow", actor5)
# char11=Character.new("Arya", actor1)
# char12=Character.new("Michael", actor3)
# char13=Character.new("Spiderman", actor7)
# app1=Appearance.new(char1, movie1)
# app2=Appearance.new(char2, movie1)
# app3=Appearance.new(char3, movie1)
# app4=Appearance.new(char4, movie1)
# app5=Appearance.new(char5, movie1)
# app6=Appearance.new(char6, movie1)
# app7=Appearance.new(char7, movie2)
# app8=Appearance.new(char8, movie2)
# app9=Appearance.new(char1, show1)
# app10=Appearance.new(char4, show1)
# app11=Appearance.new(char5, show1)
# app12=Appearance.new(char13, show1)
# app13=Appearance.new(char9, show2)
# app14=Appearance.new(char10, show2)
# app15=Appearance.new(char11, show2)
# app16=Appearance.new(char12, show3)
# app17=Appearance.new(char1, show2)

# crowdfund

# user1=User.new("James")
# user2=User.new("Jeanne")
# user3=User.new("Ada")
# user4=User.new("Soren")
# user5=User.new("Nika")
# user6=User.new("David")
# user7=User.new("Ginny")
# project1=Project.new("Album", user1, 10000)
# project2=Project.new("Movie", user4, 100000)
# project3=Project.new("Software", user2, 300000)
# project4=Project.new("Invention", user5, 400000)
# pledge1=Pledge.new(user2, project1, 6000)
# pledge2=Pledge.new(user5, project1, 7000)
# pledge3=Pledge.new(user1, project2, 15000)
# pledge4=Pledge.new(user1, project3, 15001)
# pledge5=Pledge.new(user3, project2, 8000)
# pledge6=Pledge.new(user4, project3, 65)
# pledge7=Pledge.new(user2, project2, 100)

# gym
gym1=Location.new("Downtown")
gym2=Location.new("Uptown")
gym3=Location.new("Westchester")
client1=Client.new("Carl")
client2=Client.new("Cara")
client3=Client.new("Clarissa")
client4=Client.new("Clarke")
client5=Client.new("Connor")
client6=Client.new("Colin")
trainer1=Trainer.new("Tom")
trainer2=Trainer.new("Tracy")
trainer3=Trainer.new("Tara")
trainer4=Trainer.new("Timothy")
trainer1.start_training(client1)
trainer1.start_training(client2)
trainer1.start_training(client3)
trainer2.start_training(client4)
trainer3.start_training(client5)
trainer4.start_training(client6)
trainer1.works_at(gym1)
trainer2.works_at(gym2)
trainer3.works_at(gym3)
trainer4.works_at(gym2)


Pry.start
0